### PR TITLE
Delete comments

### PR DESCRIPTION
**Pull request by PiaDue**
- fixed private comment bug
- implemented delete comment feature (for users' own comments)

- [ ] #148

### CODE REVIEW

**Review by justingebert — APPROVED** [review]
👍 
one bug is still there:
RoadmapGoalTextbox.tsx:99 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `RoadmapGoalTextbox`. See https://reactjs.org/link/warning-keys for more information.
    at div
    at RoadmapGoalTextbox (http://localhost:5173/src/components/RoadmapGoalTextbox.tsx?t=1706622508454:23:31)
    at div
    at div
    at div
    at RoadmapPage (http://localhost:5173/src/pages/RoadmapPage.tsx?t=1706622508454:26:37)
    at GoalsProvider (http://localhost:5173/src/contexts/GoalContext.tsx?t=1706622508454:30:33)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=9e1fe38c:3467:5)
    at Routes (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=9e1fe38c:3850:5)
    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=9e1fe38c:3797:15)
    at BrowserRouter (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=9e1fe38c:4459:5)
    at FlashProvider (http://localhost:5173/src/contexts/FlashContext.tsx:23:33)
    at App (http://localhost:5173/src/App.tsx?t=1706622508454:43:26)
    at AuthProvider (http://localhost:5173/src/contexts/AuthContext.tsx?t=1706622508454:21:32)
    at AppWrapper
overrideMethod @ console.js:213
printWarning @ react_jsx-dev-runtime.js?v=9e1fe38c:62
error @ react_jsx-dev-runtime.js?v=9e1fe38c:46
validateExplicitKey @ react_jsx-dev-runtime.js?v=9e1fe38c:722
validateChildKeys @ react_jsx-dev-runtime.js?v=9e1fe38c:735
jsxWithValidation @ react_jsx-dev-runtime.js?v=9e1fe38c:843
RoadmapGoalTextbox @ RoadmapGoalTextbox.tsx:99
renderWithHooks @ chunk-MMW4JUSU.js?v=9e1fe38c:12169
updateFunctionComponent @ chunk-MMW4JUSU.js?v=9e1fe38c:14575
beginWork @ chunk-MMW4JUSU.js?v=9e1fe38c:15910
beginWork$1 @ chunk-MMW4JUSU.js?v=9e1fe38c:19747
performUnitOfWork @ chunk-MMW4JUSU.js?v=9e1fe38c:19192
workLoopSync @ chunk-MMW4JUSU.js?v=9e1fe38c:19131
renderRootSync @ chunk-MMW4JUSU.js?v=9e1fe38c:19110
performSyncWorkOnRoot @ chunk-MMW4JUSU.js?v=9e1fe38c:18868
flushSyncCallbacks @ chunk-MMW4JUSU.js?v=9e1fe38c:9133
(anonym) @ chunk-MMW4JUSU.js?v=9e1fe38c:18621
16 weitere Frames anzeigen
Weniger anzeigen


image

**when unfolding the commetn section with multiple comments**

**Review by justingebert — COMMENTED** [review]
when commenting with empty input server Crashes:
Error creating comment: Error: Comment validation failed: comment: Path `comment` is required.
    at ValidationError.inspect (C:\Users\justi\Documents\PROJECTS\Uni\HypnoBuddy\b4-hypnobuddy\Backend\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at formatWithOptions (node:internal/util/inspect:2160:10)
    at console.value (node:internal/console/constructor:351:14)
    at console.warn (node:internal/console/constructor:384:61)
    at C:\Users\justi\Documents\PROJECTS\Uni\HypnoBuddy\b4-hypnobuddy\Backend\controllers\goalController.js:406:21
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\justi\Documents\PROJECTS\Uni\HypnoBuddy\b4-hypnobuddy\Backend\controllers\goalController.js:6:65) {
  errors: {
    comment: ValidatorError: Path `comment` is required.
        at validate (C:\Users\justi\Documents\PROJECTS\Uni\HypnoBuddy\b4-hypnobuddy\Backend\node_modules\mongoose\lib\schematype.js:1365:13)
        at SchemaType.doValidate (C:\Users\justi\Documents\PROJECTS\Uni\HypnoBuddy\b4-hypnobuddy\Backend\node_modules\mongoose\lib\schematype.js:1349:7)
        at C:\Users\justi\Documents\PROJECTS\Uni\HypnoBuddy\b4-hypnobuddy\Backend\node_modules\mongoose\lib\document.js:2985:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'comment',
      value: '',
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'Comment validation failed'
}

**Review by justingebert — APPROVED** [review]
👍

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-ALWAQYkM1Ln3So62

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]
google_cloud_run_v2_service.backend: Refreshing state... [id=projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend]
google_cloud_run_service_iam_binding.default: Refreshing state... [id=v1/projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend/roles/run.invoker]
google_cloud_run_v2_service.backend: Drift detected (update)

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-ZpvPQXyN8N9DxUei

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]
google_cloud_run_v2_service.backend: Refreshing state... [id=projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend]
google_cloud_run_service_iam_binding.default: Refreshing state... [id=v1/projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend/roles/run.invoker]
google_cloud_run_v2_service.backend: Drift detected (update)

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Review by snahn2209 — APPROVED** [review]

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-7jot1urUrJjLaLzG

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]
google_cloud_run_v2_service.backend: Refreshing state... [id=projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend]
google_cloud_run_service_iam_binding.default: Refreshing state... [id=v1/projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend/roles/run.invoker]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Pull request merged**
