### PR TITLE
Dos and donts tests

### PR DESCRIPTION
**Pull request by NataliiaRemezova**
Merging Jest and Cypress tests into main

### CODE REVIEW

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-Soyp1s18DBGw1CLV

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]
google_cloud_run_v2_service.backend: Refreshing state... [id=projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend]
google_cloud_run_service_iam_binding.default: Refreshing state... [id=v1/projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend/roles/run.invoker]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-vZ5opo21PhCp5Jtz

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]
google_cloud_run_v2_service.backend: Refreshing state... [id=projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend]
google_cloud_run_service_iam_binding.default: Refreshing state... [id=v1/projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend/roles/run.invoker]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-6QwmivWhUEF6rLHt

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]
google_cloud_run_v2_service.backend: Refreshing state... [id=projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend]
google_cloud_run_service_iam_binding.default: Refreshing state... [id=v1/projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend/roles/run.invoker]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-cWnccq5EZAuTJ1QK

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 1s [id=projects/897359304801/secrets/mongo_url/versions/1]
google_cloud_run_v2_service.backend: Refreshing state... [id=projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend]
google_cloud_run_service_iam_binding.default: Refreshing state... [id=v1/projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend/roles/run.invoker]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-psp63HBGnqL77FFn

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]
google_cloud_run_v2_service.backend: Refreshing state... [id=projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend]
google_cloud_run_service_iam_binding.default: Refreshing state... [id=v1/projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend/roles/run.invoker]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-Yi96XGeVYRcm8QfJ

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]
google_cloud_run_v2_service.backend: Refreshing state... [id=projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend]
google_cloud_run_service_iam_binding.default: Refreshing state... [id=v1/projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend/roles/run.invoker]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Review by justingebert — APPROVED** [review]
looks godd, i dont really understand how to run the tests,
when trying npx cypress run i got the followin issue:
DevTools listening on ws://127.0.0.1:60832/devtools/browser/91f027a7-db46-4e87-9464-faf247df278d
Could not load a Cypress configuration file because there are multiple matches.

We've found 2 Cypress configuration files named
cypress.config.ts, cypress.config.js at the location below: 

maybe add to tscvonfig to exclude or tsignore

**Comment by NataliiaRemezova** [comment]
> maybe add to tscvonfig to exclude or tsignore

@justingebert, I've added exclude to the tsconfig, could you please test if cypress opens?
To open cypress, you should first start backend and frontend, because cypress needs a version of the app that runs (locally) in browser
To start cypress, you should use npx cypress open in the Frontend/hypno-buddy directory

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-L1KtBYw7emPTKCLw

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]
google_cloud_run_v2_service.backend: Refreshing state... [id=projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend]
google_cloud_run_service_iam_binding.default: Refreshing state... [id=v1/projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend/roles/run.invoker]
google_cloud_run_service_iam_binding.default: Drift detected (update)
google_cloud_run_v2_service.backend: Drift detected (delete)

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:

  # google_cloud_run_v2_service.backend has been deleted
  - resource "google_cloud_run_v2_service" "backend" {
        id                      = "projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend"
      - location                = "europe-west1" -> null
      - name                    = "hypnobuddy-backend" -> null
        # (24 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # google_cloud_run_service_iam_binding.default will be updated in-place
  ~ resource "google_cloud_run_service_iam_binding" "default" {
        id       = "v1/projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend/roles/run.invoker"
      ~ members  = [
          + "allUsers",
        ]
        # (5 unchanged attributes hidden)
    }

  # google_cloud_run_v2_service.backend will be created
  + resource "google_cloud_run_v2_service" "backend" {
      + conditions              = (known after apply)
      + create_time             = (known after apply)
      + creator                 = (known after apply)
      + delete_time             = (known after apply)
      + effective_annotations   = (known after apply)
      + effective_labels        = (known after apply)
      + etag                    = (known after apply)
      + expire_time             = (known after apply)
      + generation              = (known after apply)
      + id                      = (known after apply)
      + ingress                 = (known after apply)
      + last_modifier           = (known after apply)
      + latest_created_revision = (known after apply)
      + latest_ready_revision   = (known after apply)
      + launch_stage            = (known after apply)
      + location                = "europe-west1"
      + name                    = "hypnobuddy-backend"
      + observed_generation     = (known after apply)
      + project                 = "imi-b4"
      + reconciling             = (known after apply)
      + terminal_condition      = (known after apply)
      + terraform_labels        = (known after apply)
      + traffic_statuses        = (known after apply)
      + uid                     = (known after apply)
      + update_time             = (known after apply)
      + uri                     = (known after apply)

      + template {
          + max_instance_request_concurrency = (known after apply)
          + service_account                  = (known after apply)
          + timeout                          = (known after apply)

          + containers {
              + image = "justingebert/hypnobuddy-backend:latest"

              + env {
                  + name  = "MONGO_URL"
                  + value = (sensitive value)
                }
            }
        }
    }

Plan: 1 to add, 1 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-ZhgvPH1bQz6Gv8em

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]
google_cloud_run_v2_service.backend: Refreshing state... [id=projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend]
google_cloud_run_service_iam_binding.default: Refreshing state... [id=v1/projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend/roles/run.invoker]
google_cloud_run_service_iam_binding.default: Drift detected (update)
google_cloud_run_v2_service.backend: Drift detected (delete)

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:

  # google_cloud_run_v2_service.backend has been deleted
  - resource "google_cloud_run_v2_service" "backend" {
        id                      = "projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend"
      - location                = "europe-west1" -> null
      - name                    = "hypnobuddy-backend" -> null
        # (24 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # google_cloud_run_service_iam_binding.default will be updated in-place
  ~ resource "google_cloud_run_service_iam_binding" "default" {
        id       = "v1/projects/imi-b4/locations/europe-west1/services/hypnobuddy-backend/roles/run.invoker"
      ~ members  = [
          + "allUsers",
        ]
        # (5 unchanged attributes hidden)
    }

  # google_cloud_run_v2_service.backend will be created
  + resource "google_cloud_run_v2_service" "backend" {
      + conditions              = (known after apply)
      + create_time             = (known after apply)
      + creator                 = (known after apply)
      + delete_time             = (known after apply)
      + effective_annotations   = (known after apply)
      + effective_labels        = (known after apply)
      + etag                    = (known after apply)
      + expire_time             = (known after apply)
      + generation              = (known after apply)
      + id                      = (known after apply)
      + ingress                 = (known after apply)
      + last_modifier           = (known after apply)
      + latest_created_revision = (known after apply)
      + latest_ready_revision   = (known after apply)
      + launch_stage            = (known after apply)
      + location                = "europe-west1"
      + name                    = "hypnobuddy-backend"
      + observed_generation     = (known after apply)
      + project                 = "imi-b4"
      + reconciling             = (known after apply)
      + terminal_condition      = (known after apply)
      + terraform_labels        = (known after apply)
      + traffic_statuses        = (known after apply)
      + uid                     = (known after apply)
      + update_time             = (known after apply)
      + uri                     = (known after apply)

      + template {
          + max_instance_request_concurrency = (known after apply)
          + service_account                  = (known after apply)
          + timeout                          = (known after apply)

          + containers {
              + image = "justingebert/hypnobuddy-backend:latest"

              + env {
                  + name  = "MONGO_URL"
                  + value = (sensitive value)
                }
            }
        }
    }

Plan: 1 to add, 1 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Pull request merged**
