### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by justingebert**
please test,
should get a terraform plan and firbase frontend hosting on pr to test if both will work,

### CODE REVIEW

**Comment by justingebert** [comment]
add localhost of mongodb

**Comment by justingebert** [comment]
add url change insturctions to readme.md

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-9TPWgVabw71bqkZL

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_cloud_run_service_iam_binding.default will be created
  + resource "google_cloud_run_service_iam_binding" "default" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + location = "europe-west1"
      + members  = [
          + "allUsers",
        ]
      + project  = (known after apply)
      + role     = "roles/run.invoker"
      + service  = "hypnobuddy-backend"
    }

  # google_cloud_run_v2_service.backend will be created
  + resource "google_cloud_run_v2_service" "backend" {
      + conditions              = (known after apply)
      + create_time             = (known after apply)
      + creator                 = (known after apply)
      + delete_time             = (known after apply)
      + effective_annotations   = (known after apply)
      + effective_labels        = (known after apply)
      + etag                    = (known after apply)
      + expire_time             = (known after apply)
      + generation              = (known after apply)
      + id                      = (known after apply)
      + ingress                 = (known after apply)
      + last_modifier           = (known after apply)
      + latest_created_revision = (known after apply)
      + latest_ready_revision   = (known after apply)
      + launch_stage            = (known after apply)
      + location                = "europe-west1"
      + name                    = "hypnobuddy-backend"
      + observed_generation     = (known after apply)
      + project                 = "imi-b4"
      + reconciling             = (known after apply)
      + terminal_condition      = (known after apply)
      + terraform_labels        = (known after apply)
      + traffic_statuses        = (known after apply)
      + uid                     = (known after apply)
      + update_time             = (known after apply)
      + uri                     = (known after apply)

      + template {
          + max_instance_request_concurrency = (known after apply)
          + service_account                  = (known after apply)
          + timeout                          = (known after apply)

          + containers {
              + image = "justingebert/hypnobuddy:test14"

              + env {
                  + name  = "MONGO_URL"
                  + value = (sensitive value)
                }
            }
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Comment by justingebert** [comment]
change cookies to work in dev env -> using enviroment vars

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-tUTqo4dciRnmjZeo

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_cloud_run_service_iam_binding.default will be created
  + resource "google_cloud_run_service_iam_binding" "default" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + location = "europe-west1"
      + members  = [
          + "allUsers",
        ]
      + project  = (known after apply)
      + role     = "roles/run.invoker"
      + service  = "hypnobuddy-backend"
    }

  # google_cloud_run_v2_service.backend will be created
  + resource "google_cloud_run_v2_service" "backend" {
      + conditions              = (known after apply)
      + create_time             = (known after apply)
      + creator                 = (known after apply)
      + delete_time             = (known after apply)
      + effective_annotations   = (known after apply)
      + effective_labels        = (known after apply)
      + etag                    = (known after apply)
      + expire_time             = (known after apply)
      + generation              = (known after apply)
      + id                      = (known after apply)
      + ingress                 = (known after apply)
      + last_modifier           = (known after apply)
      + latest_created_revision = (known after apply)
      + latest_ready_revision   = (known after apply)
      + launch_stage            = (known after apply)
      + location                = "europe-west1"
      + name                    = "hypnobuddy-backend"
      + observed_generation     = (known after apply)
      + project                 = "imi-b4"
      + reconciling             = (known after apply)
      + terminal_condition      = (known after apply)
      + terraform_labels        = (known after apply)
      + traffic_statuses        = (known after apply)
      + uid                     = (known after apply)
      + update_time             = (known after apply)
      + uri                     = (known after apply)

      + template {
          + max_instance_request_concurrency = (known after apply)
          + service_account                  = (known after apply)
          + timeout                          = (known after apply)

          + containers {
              + image = "justingebert/hypnobuddy:test14"

              + env {
                  + name  = "MONGO_URL"
                  + value = (sensitive value)
                }
            }
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-QLMa9qsAn8B8TnNw

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_cloud_run_service_iam_binding.default will be created
  + resource "google_cloud_run_service_iam_binding" "default" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + location = "europe-west1"
      + members  = [
          + "allUsers",
        ]
      + project  = (known after apply)
      + role     = "roles/run.invoker"
      + service  = "hypnobuddy-backend"
    }

  # google_cloud_run_v2_service.backend will be created
  + resource "google_cloud_run_v2_service" "backend" {
      + conditions              = (known after apply)
      + create_time             = (known after apply)
      + creator                 = (known after apply)
      + delete_time             = (known after apply)
      + effective_annotations   = (known after apply)
      + effective_labels        = (known after apply)
      + etag                    = (known after apply)
      + expire_time             = (known after apply)
      + generation              = (known after apply)
      + id                      = (known after apply)
      + ingress                 = (known after apply)
      + last_modifier           = (known after apply)
      + latest_created_revision = (known after apply)
      + latest_ready_revision   = (known after apply)
      + launch_stage            = (known after apply)
      + location                = "europe-west1"
      + name                    = "hypnobuddy-backend"
      + observed_generation     = (known after apply)
      + project                 = "imi-b4"
      + reconciling             = (known after apply)
      + terminal_condition      = (known after apply)
      + terraform_labels        = (known after apply)
      + traffic_statuses        = (known after apply)
      + uid                     = (known after apply)
      + update_time             = (known after apply)
      + uri                     = (known after apply)

      + template {
          + max_instance_request_concurrency = (known after apply)
          + service_account                  = (known after apply)
          + timeout                          = (known after apply)

          + containers {
              + image = "justingebert/hypnobuddy:test14"

              + env {
                  + name  = "MONGO_URL"
                  + value = (sensitive value)
                }
            }
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-3pD1uCXDFdKMjYRj

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_cloud_run_service_iam_binding.default will be created
  + resource "google_cloud_run_service_iam_binding" "default" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + location = "europe-west1"
      + members  = [
          + "allUsers",
        ]
      + project  = (known after apply)
      + role     = "roles/run.invoker"
      + service  = "hypnobuddy-backend"
    }

  # google_cloud_run_v2_service.backend will be created
  + resource "google_cloud_run_v2_service" "backend" {
      + conditions              = (known after apply)
      + create_time             = (known after apply)
      + creator                 = (known after apply)
      + delete_time             = (known after apply)
      + effective_annotations   = (known after apply)
      + effective_labels        = (known after apply)
      + etag                    = (known after apply)
      + expire_time             = (known after apply)
      + generation              = (known after apply)
      + id                      = (known after apply)
      + ingress                 = (known after apply)
      + last_modifier           = (known after apply)
      + latest_created_revision = (known after apply)
      + latest_ready_revision   = (known after apply)
      + launch_stage            = (known after apply)
      + location                = "europe-west1"
      + name                    = "hypnobuddy-backend"
      + observed_generation     = (known after apply)
      + project                 = "imi-b4"
      + reconciling             = (known after apply)
      + terminal_condition      = (known after apply)
      + terraform_labels        = (known after apply)
      + traffic_statuses        = (known after apply)
      + uid                     = (known after apply)
      + update_time             = (known after apply)
      + uri                     = (known after apply)

      + template {
          + max_instance_request_concurrency = (known after apply)
          + service_account                  = (known after apply)
          + timeout                          = (known after apply)

          + containers {
              + image = "justingebert/hypnobuddy:test14"

              + env {
                  + name  = "MONGO_URL"
                  + value = (sensitive value)
                }
            }
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-v5r3LEP4JLACKqfo

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_cloud_run_service_iam_binding.default will be created
  + resource "google_cloud_run_service_iam_binding" "default" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + location = "europe-west1"
      + members  = [
          + "allUsers",
        ]
      + project  = (known after apply)
      + role     = "roles/run.invoker"
      + service  = "hypnobuddy-backend"
    }

  # google_cloud_run_v2_service.backend will be created
  + resource "google_cloud_run_v2_service" "backend" {
      + conditions              = (known after apply)
      + create_time             = (known after apply)
      + creator                 = (known after apply)
      + delete_time             = (known after apply)
      + effective_annotations   = (known after apply)
      + effective_labels        = (known after apply)
      + etag                    = (known after apply)
      + expire_time             = (known after apply)
      + generation              = (known after apply)
      + id                      = (known after apply)
      + ingress                 = (known after apply)
      + last_modifier           = (known after apply)
      + latest_created_revision = (known after apply)
      + latest_ready_revision   = (known after apply)
      + launch_stage            = (known after apply)
      + location                = "europe-west1"
      + name                    = "hypnobuddy-backend"
      + observed_generation     = (known after apply)
      + project                 = "imi-b4"
      + reconciling             = (known after apply)
      + terminal_condition      = (known after apply)
      + terraform_labels        = (known after apply)
      + traffic_statuses        = (known after apply)
      + uid                     = (known after apply)
      + update_time             = (known after apply)
      + uri                     = (known after apply)

      + template {
          + max_instance_request_concurrency = (known after apply)
          + service_account                  = (known after apply)
          + timeout                          = (known after apply)

          + containers {
              + image = "justingebert/hypnobuddy:test14"

              + env {
                  + name  = "MONGO_URL"
                  + value = (sensitive value)
                }
            }
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Comment by justingebert** [comment]
Terraform Plan Output:
```Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/hypnobuddy/hypnobuddy/runs/run-q6F7YSSBvtLtaqvT

Waiting for the plan to start...

Terraform v1.7.1
on linux_amd64
Initializing plugins and modules...
data.google_secret_manager_secret_version.mongo_url: Refreshing...
data.google_secret_manager_secret_version.mongo_url: Refresh complete after 0s [id=projects/897359304801/secrets/mongo_url/versions/1]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_cloud_run_service_iam_binding.default will be created
  + resource "google_cloud_run_service_iam_binding" "default" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + location = "europe-west1"
      + members  = [
          + "allUsers",
        ]
      + project  = (known after apply)
      + role     = "roles/run.invoker"
      + service  = "hypnobuddy-backend"
    }

  # google_cloud_run_v2_service.backend will be created
  + resource "google_cloud_run_v2_service" "backend" {
      + conditions              = (known after apply)
      + create_time             = (known after apply)
      + creator                 = (known after apply)
      + delete_time             = (known after apply)
      + effective_annotations   = (known after apply)
      + effective_labels        = (known after apply)
      + etag                    = (known after apply)
      + expire_time             = (known after apply)
      + generation              = (known after apply)
      + id                      = (known after apply)
      + ingress                 = (known after apply)
      + last_modifier           = (known after apply)
      + latest_created_revision = (known after apply)
      + latest_ready_revision   = (known after apply)
      + launch_stage            = (known after apply)
      + location                = "europe-west1"
      + name                    = "hypnobuddy-backend"
      + observed_generation     = (known after apply)
      + project                 = "imi-b4"
      + reconciling             = (known after apply)
      + terminal_condition      = (known after apply)
      + terraform_labels        = (known after apply)
      + traffic_statuses        = (known after apply)
      + uid                     = (known after apply)
      + update_time             = (known after apply)
      + uri                     = (known after apply)

      + template {
          + max_instance_request_concurrency = (known after apply)
          + service_account                  = (known after apply)
          + timeout                          = (known after apply)

          + containers {
              + image = "justingebert/hypnobuddy:test14"

              + env {
                  + name  = "MONGO_URL"
                  + value = (sensitive value)
                }
            }
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

**Review by snahn2209 — APPROVED** [review]
tested everything, works fine!

**Pull request merged**
