### PR TITLE
Styling flashmessages

### PR DESCRIPTION
**Pull request by snahn2209**
does no look great and it's not perfect but I think it will do for now (was not able to do it any cleaner :/ )

-> if there are other suggestions, please comment

### CODE REVIEW

**Comment by justingebert** [comment]
> does no look great and it's not perfect but I think it will do for now (was not able to do it any cleaner :/ )
> 
> -> if there are other suggestions, please comment

maybe at the bottom right as a card? 
also if the login is wrong there a bug and no flash message is displayed

**Review by justingebert — COMMENTED** [review]
maybe at the bottom right as a card? but always visibvle without scrollin

**Review by maile000 — APPROVED** [review]

**Review by justingebert — COMMENTED** [review]
👍 looks great!

**Review by justingebert — APPROVED** [review]
👍

**Pull request merged**
